#!/bin/bash
appdir=/usr/share/applications
filelist="$HOME/.local/share/applications/mimeapps.list \
          $HOME/.config/mimeapps.list
          $appdir/defaults.list
          $appdir/mimeinfo.cache"
for f in $filelist; do
    [ -f "$f" ] && lists="$lists $f"
done
[ -n "$lists" ] || exit 1
for f in "$@"; do
    [ -e "$f" ] || {
        echo "$f not found"
        continue
    }
    type="$(file -biL "$f" | cut -d ';' -f 1)"
    appfile="$(grep -h $type $lists | head -1 | cut -d = -f 2- | cut -d ';' -f 1)"
    [ -n "$appfile" ] || {
        echo "No default app for this file type: $type" >&2
        continue
    }
    cmd="$(sed -n '/^\[Desktop Entry]/,/^\[/p' "$appdir/$appfile" |
            grep "^Exec=" | cut -d = -f 2- | sed 's/ *%[Uf]//')"
    app=$(echo $cmd | cut -d' ' -f1)
    which $app >/dev/null || {
        which apt-file >/dev/null || {
            sudo apt install apt-file
            apt-file update
        }
        pkg="$(apt-file -lx search "bin/$app$" | sort -u)"
        sudo apt install -y $pkg
    }
    $cmd "$f" &>/dev/null &
    disown
done
