#!/bin/bash
filelist="$HOME/.local/share/applications/mimeapps.list \
          /usr/share/applications/defaults.list"
appdir=/usr/share/applications
for f in $filelist; do
    [ -f "$f" ] && lists="$lists $f"
done
[ -n "$lists" ] || exit 1
for f in "$@"; do
    [ -e "$f" ] || {
        echo "$f not found"
        continue
    }
    type="$(file -biL "$f" | cut -d ';' -f 1)"
    app="$(grep -h $type $lists | head -1 | cut -d = -f 2- | cut -d ';' -f 1)"
    which "$app" >/dev/null || sudo apt install -y "$(echo $app | sed s/\.desktop//)"
    $(sed -n '/^\[Desktop Entry]/,/^\[/p' "$appdir/$app" |
        grep "^Exec=" | cut -d = -f 2- | sed 's/ *%U//') "$f" &>/dev/null &
    disown
done
